@ECHO OFF

:choice1
set /P c=Export the PRE ETL schema (PRE_ETL_OWNER) on (mydb) : continue[Y/N]?
if /I "%c%" EQU "Y" goto :doit1
if /I "%c%" EQU "N" goto :dont
goto :choice1

:doit1

:choice2
set /P p=PRE_ETL_OWNER password :
if /I "%p%" NEQ "" goto :doit2
goto :choice2

:doit2

exp userid=pre_etl_owner/%p%@mydb FILE=..\exports\export_pre_etl FEEDBACK=1000 STATISTICS=none BUFFER=1000000 TABLES=(AUD_GENERATOR_LOG, AUD_PRE_ETL_COMMENTS, AUD_PRE_ETL_DB2_COLUMNS, AUD_PRE_ETL_DB2_TABLES, AUD_PRE_ETL_FIND_SWAP, AUD_PRE_ETL_JSON_DOCUMENT, AUD_PRE_ETL_JSON_LINES, AUD_PRE_ETL_MAPPED, AUD_PRE_ETL_MIGRATION_DETAIL, AUD_PRE_ETL_MIGRATION_GROUPS, AUD_PRE_ETL_MIGRATION_HEADER, AUD_PRE_ETL_MIGRATION_SRC, AUD_PRE_ETL_MIGRATION_SRC_INLI, AUD_PRE_ETL_MR_GROUP, AUD_PRE_ETL_PARAMS, AUD_PRE_ETL_RELATED_JSON_LINES, AUD_PRE_ETL_RUN_CONTEXTS, AUD_PRE_ETL_SUBSTITUTION_VALUE, AUD_PRE_ETL_DOC_VALID_CONTEXTS, AUD_PRE_ETL_MIGRATION_RUN_HINT, AUD_PRE_ETL_MIGRATION_LIBS, AUD_PRE_ETL_MIGRATION_CODE_LIB, PRE_ETL_COMMENTS, PRE_ETL_DB2_COLUMNS, PRE_ETL_DB2_TABLES, PRE_ETL_FIND_SWAP, PRE_ETL_JSON_DOCUMENT, PRE_ETL_JSON_LINES, PRE_ETL_MAPPED, PRE_ETL_MIGRATION_DETAIL, PRE_ETL_MIGRATION_GROUPS, PRE_ETL_MIGRATION_HEADER, PRE_ETL_MIGRATION_SRC, PRE_ETL_MIGRATION_SRC_INLINE_V, PRE_ETL_MR_GROUP, PRE_ETL_PARAMS, PRE_ETL_RELATED_JSON_LINES, PRE_ETL_RUN_CONTEXTS, PRE_ETL_SUBSTITUTION_VALUES, PRE_ETL_DOC_VALID_CONTEXTS, PRE_ETL_MIGRATION_LIBS, PRE_ETL_MIGRATION_CODE_LIB, PRE_ETL_MIGRATION_RUN_HINT, ON_ETL_LOG, ON_ETL_PARAMS)

REM =======================================================================================================
REM : TO IMPORT : See - DEV02MCP1_import_etl_owner.cmd
REM =======================================================================================================

ECHO Export Attempted : See above.

PAUSE

exit

:dont

echo "Aborted."

PAUSE

exit

