@ECHO OFF

:choice1
set /P c=IMPORT the PRE ETL database : continue[Y/N]?
if /I "%c%" EQU "Y" goto :doit1
if /I "%c%" EQU "N" goto :dont
goto :choice1

:doit1

:choice2
set /P d=Target user/password@database :
if /I "%d%" NEQ "" goto :doit2
goto :choice2

:doit2

echo **************************************************************
echo **
echo ** Importing Into : %d%
echo **
echo ** ON_ETL_LOG
echo ** AUD_GENERATOR_LOG
echo ** AUD_PRE_ETL_COMMENTS
echo ** AUD_PRE_ETL_DB2_COLUMNS
echo ** AUD_PRE_ETL_DB2_TABLES
echo ** AUD_PRE_ETL_FIND_SWAP
echo ** AUD_PRE_ETL_JSON_DOCUMENT
echo ** AUD_PRE_ETL_JSON_LINES
echo ** AUD_PRE_ETL_MAPPED
echo ** AUD_PRE_ETL_MIGRATION_DETAIL
echo ** AUD_PRE_ETL_MIGRATION_GROUPS
echo ** AUD_PRE_ETL_MIGRATION_HEADER
echo ** AUD_PRE_ETL_MIGRATION_SRC
echo ** AUD_PRE_ETL_MIGRATION_SRC_INLI
echo ** AUD_PRE_ETL_MR_GROUP
echo ** AUD_PRE_ETL_PARAMS
echo ** AUD_PRE_ETL_RELATED_JSON_LINES
echo ** AUD_PRE_ETL_RUN_CONTEXTS
echo ** AUD_PRE_ETL_SUBSTITUTION_VALUE
echo ** AUD_PRE_ETL_DOC_VALID_CONTEXTS
echo ** AUD_PRE_ETL_MIGRATION_RUN_HINT
echo ** AUD_PRE_ETL_MIGRATION_LIBS
echo ** AUD_PRE_ETL_MIGRATION_CODE_LIB
echo ** PRE_ETL_COMMENTS
echo ** PRE_ETL_DB2_COLUMNS
echo ** PRE_ETL_DB2_TABLES
echo ** PRE_ETL_FIND_SWAP
echo ** PRE_ETL_JSON_DOCUMENT
echo ** PRE_ETL_JSON_LINES
echo ** PRE_ETL_MAPPED
echo ** PRE_ETL_MIGRATION_DETAIL
echo ** PRE_ETL_MIGRATION_GROUPS
echo ** PRE_ETL_MIGRATION_HEADER
echo ** PRE_ETL_MIGRATION_SRC
echo ** PRE_ETL_MIGRATION_SRC_INLINE_V
echo ** PRE_ETL_MR_GROUP
echo ** PRE_ETL_PARAMS
echo ** PRE_ETL_RELATED_JSON_LINES
echo ** PRE_ETL_RUN_CONTEXTS
echo ** PRE_ETL_SUBSTITUTION_VALUES
echo ** PRE_ETL_DOC_VALID_CONTEXTS
echo ** PRE_ETL_MIGRATION_RUN_HINT
echo ** PRE_ETL_MIGRATION_LIBS
echo ** PRE_ETL_MIGRATION_CODE_LIB
echo ** ON_ETL_LOG
echo ** ON_ETL_PARAMS
echo **
echo **************************************************************

C:

cd ..\exports

sqlplus %d% @prepare_target.sql

imp userid=%d% FILE=export_pre_etl TABLES=(AUD_GENERATOR_LOG, AUD_PRE_ETL_COMMENTS, AUD_PRE_ETL_DB2_COLUMNS, AUD_PRE_ETL_DB2_TABLES, AUD_PRE_ETL_FIND_SWAP, AUD_PRE_ETL_JSON_DOCUMENT, AUD_PRE_ETL_JSON_LINES, AUD_PRE_ETL_MAPPED, AUD_PRE_ETL_MIGRATION_DETAIL, AUD_PRE_ETL_MIGRATION_GROUPS, AUD_PRE_ETL_MIGRATION_HEADER, AUD_PRE_ETL_MIGRATION_SRC, AUD_PRE_ETL_MIGRATION_SRC_INLI, AUD_PRE_ETL_MR_GROUP, AUD_PRE_ETL_PARAMS, AUD_PRE_ETL_RELATED_JSON_LINES, AUD_PRE_ETL_RUN_CONTEXTS, AUD_PRE_ETL_SUBSTITUTION_VALUE, AUD_PRE_ETL_DOC_VALID_CONTEXTS, AUD_PRE_ETL_MIGRATION_RUN_HINT, AUD_PRE_ETL_MIGRATION_LIBS, AUD_PRE_ETL_MIGRATION_CODE_LIB, PRE_ETL_COMMENTS, PRE_ETL_DB2_COLUMNS, PRE_ETL_DB2_TABLES, PRE_ETL_FIND_SWAP, PRE_ETL_JSON_DOCUMENT, PRE_ETL_JSON_LINES, PRE_ETL_MAPPED, PRE_ETL_MIGRATION_DETAIL, PRE_ETL_MIGRATION_GROUPS, PRE_ETL_MIGRATION_HEADER, PRE_ETL_MIGRATION_SRC, PRE_ETL_MIGRATION_SRC_INLINE_V, PRE_ETL_MR_GROUP, PRE_ETL_PARAMS, PRE_ETL_RELATED_JSON_LINES, PRE_ETL_RUN_CONTEXTS, PRE_ETL_SUBSTITUTION_VALUES, PRE_ETL_DOC_VALID_CONTEXTS, PRE_ETL_MIGRATION_RUN_HINT, PRE_ETL_MIGRATION_LIBS, PRE_ETL_MIGRATION_CODE_LIB, ON_ETL_LOG, ON_ETL_PARAMS) DATA_ONLY=Y CONSTRAINTS=N FEEDBACK=1000 BUFFER=1000000

sqlplus %d% @lift_sequences.sql

ECHO Import Completed : See above for any errors or warnings...

PAUSE

exit

:dont

echo "Aborted."

PAUSE

exit

